# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# Simplified goreleaser config for fork releases
version: 2

project_name: crush

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"

before:
  hooks:
    - go mod tidy
    - rm -rf completions manpages
    - mkdir -p completions manpages
    - sh -c 'go run . completion bash >./completions/crush.bash'
    - sh -c 'go run . completion zsh >./completions/crush.zsh'
    - sh -c 'go run . completion fish >./completions/crush.fish'
    - sh -c 'go run . man | gzip -c >./manpages/crush.1.gz'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/charmbracelet/crush/internal/version.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*
      - manpages/*
      - completions/*

nfpms:
  - formats:
      - deb
    file_name_template: "{{ .ConventionalFileName }}"
    maintainer: "Fork maintainer"
    description: "A powerful terminal-based AI assistant"
    contents:
      - src: ./completions/crush.bash
        dst: /etc/bash_completion.d/crush
      - src: ./completions/crush.fish
        dst: /usr/share/fish/vendor_completions.d/crush.fish
      - src: ./completions/crush.zsh
        dst: /usr/share/zsh/site-functions/_crush
      - src: ./manpages/crush.1.gz
        dst: /usr/share/man/man1/crush.1.gz

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
